# This is assignment 10 Christopher Fusselman

# Requirement 3

In [9]:
#Create a one-dimensional NumPy array named one_d_array of 20 random
#numbers with values between 1 – 10. Demonstrate the following
#comparison operators as universal functions:
#• <, >, <=, >=, !=, and ==

#for arrays for a random number within certain range, 
#syntax: np.array.randint(min,max,(dimensions))

import numpy as np
import array
one_d_array=np.random.randint(0, 10, (1, 20))
one_d_array
x=5

#np.random.randit(0, 10, (1, 20))


array([[3, 2, 1, 1, 4, 6, 5, 3, 6, 1, 6, 5, 8, 4, 3, 9, 7, 9, 4, 3]])

In [19]:
np.less(x,one_d_array)

array([[False, False, False, False, False,  True, False, False,  True,
        False,  True, False,  True, False, False,  True,  True,  True,
        False, False]])

In [21]:
np.greater(x,one_d_array)


array([[ True,  True,  True,  True,  True, False, False,  True, False,
         True, False, False, False,  True,  True, False, False, False,
         True,  True]])

In [22]:
np.less_equal(x,one_d_array)


array([[False, False, False, False, False,  True,  True, False,  True,
        False,  True,  True,  True, False, False,  True,  True,  True,
        False, False]])

In [23]:
np.greater_equal(x,one_d_array)




array([[ True,  True,  True,  True,  True, False,  True,  True, False,
         True, False,  True, False,  True,  True, False, False, False,
         True,  True]])

In [24]:
np.not_equal(x,two_d_array)


array([[ True,  True,  True,  True,  True,  True, False,  True,  True,
         True,  True, False,  True,  True,  True,  True,  True,  True,
         True,  True]])

In [25]:
np.equal(x,one_d_array)


array([[False, False, False, False, False, False,  True, False, False,
        False, False,  True, False, False, False, False, False, False,
        False, False]])

# Requirement 4

In [26]:
#Create a two-dimensional NumPy array named two_d_array size = (4,5) with
#any values between 11 – 34. Demonstrate the following comparison
#operators as universal functions:
#• <, >, <=, >=, !=, and ==


In [14]:
import numpy as np
import array
two_d_array=np.random.randint(11,34,(4,5))
print(two_d_array)
x=[27]

[[20 11 11 15 16]
 [15 18 19 21 22]
 [19 16 32 31 27]
 [18 22 13 18 16]]


In [15]:
np.less(x,two_d_array)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True,  True, False],
       [False, False, False, False, False]])

In [18]:
np.greater(x,two_d_array)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False, False, False],
       [ True,  True,  True,  True,  True]])

In [19]:
np.less_equal(x,two_d_array)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True,  True,  True],
       [False, False, False, False, False]])

In [20]:
np.greater_equal(x,two_d_array)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [21]:
np.not_equal(x,two_d_array)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True,  True,  True]])

In [22]:
np.equal(x,two_d_array)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False]])

In [23]:
#• count the values < 15
#• sum the values > 20
#• count the values >= 19 in each row
#• determine if any values < 12
#• determine if all values > 12
#• determine if all values in each column > 14

np.count_nonzero(two_d_array<15)

3

In [30]:
np.sum(two_d_array>20)

6

In [29]:
np.count_nonzero(two_d_array>=19, axis=1)

array([1, 3, 4, 1])

In [31]:
np.any(two_d_array<12)

True

In [33]:
np.all(two_d_array>12)

False

In [36]:
np.all(two_d_array<14, axis=1)

array([False, False, False, False])

# Requirement 5

In [47]:
#Using the inches array from Chapter 02.06, determine the number of values
#where:
#• 0.15 <= value <= 1.15
#• Use ~ and | to return the same number as & above
import numpy as np
import pandas as pd

data/seattle-weather.csv

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64